name: Test lib

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: voidzero-dev/setup-vp@v1.20.0
        with:
          node-version: '24'
          cache: true
      - run: vp install
      - run: vp check
      - run: vp test run
      - run: vp pack
